markdown: kramdown
highlighter: none
permalink: pretty
encoding: utf-8
port: 4009
main_baseurl: https://bitwarden.com
destination: _site/help

sass:
  sass_dir: ./_scss
  style: compressed

exclude:
  - node_modules
  - bitwarden-help.sln
  - package.json
  - package-lock.json
  - gulpfile.js
  - appveyor.yml
  - README.md

include:
  - '.nojekyll'

collections:
  categories:
    output: true
    permalink: /:path/
    order:
      - 01_getting-started.md
      - 02_account-management.md
      - 03_send.md
      - 04_import-export.md
      - 05_auto-fill.md
      - 06_two-step-login.md
      - 07_hosting.md
      - 08_organizations.md
      - 09_providers.md
      - 10_directory-connector.md
      - 11_login-with-sso.md
      - 12_security.md
      - 13_plans-and-pricing.md
      - 14_business.md
      - 15_miscellaneous.md
  articles:
    output: true
    permalink: /article/:name/

plugins:
  - jekyll-redirect-from
